import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export interface TechAnalysis {
  summary: string;
  trl: number;
  hypeCycle: "Innovation Trigger" | "Peak of Inflated Expectations" | "Trough of Disillusionment" | "Slope of Enlightenment" | "Plateau of Productivity";
  forecast: { year: number; growth: number }[];
  insights: string[];
  risks: string[];
  opportunities: string[];
}

export async function analyzeTechnology(tech: string): Promise<TechAnalysis> {
  const model = "gemini-2.5-flash";
  
  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error("Missing Gemini API Key");
    }

    const response = await ai.models.generateContent({
      model,
      contents: `Analyze the technology: "${tech}". 
      Provide a detailed intelligence report including:
      1. A concise summary.
      2. Estimated Technology Readiness Level (TRL) from 1 to 9.
      3. Position on the Gartner Hype Cycle.
      4. A 5-year growth forecast (relative growth score 0-100).
      5. Key insights, risks, and opportunities.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            summary: { type: Type.STRING },
            trl: { type: Type.INTEGER },
            hypeCycle: { 
              type: Type.STRING,
              enum: ["Innovation Trigger", "Peak of Inflated Expectations", "Trough of Disillusionment", "Slope of Enlightenment", "Plateau of Productivity"]
            },
            forecast: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  year: { type: Type.INTEGER },
                  growth: { type: Type.INTEGER }
                }
              }
            },
            insights: { type: Type.ARRAY, items: { type: Type.STRING } },
            risks: { type: Type.ARRAY, items: { type: Type.STRING } },
            opportunities: { type: Type.ARRAY, items: { type: Type.STRING } }
          },
          required: ["summary", "trl", "hypeCycle", "forecast", "insights", "risks", "opportunities"]
        }
      }
    });

    return JSON.parse(response.text);
  } catch (error) {
    console.warn("Gemini API failed or key missing, using mock data for demo:", error);
    // Return mock data for demo purposes
    const seed = tech.length % 5;
    const trlLevels = [3, 5, 7, 4, 6];
    const hypeCycleStages: TechAnalysis['hypeCycle'][] = [
      "Innovation Trigger", 
      "Peak of Inflated Expectations", 
      "Trough of Disillusionment", 
      "Slope of Enlightenment", 
      "Plateau of Productivity"
    ];

    return {
      summary: `This is a demo analysis for **${tech}**. In a real environment, this would be generated by the Gemini AI model. ${tech} is a rapidly evolving field with significant potential for disruption across multiple industries.`,
      trl: trlLevels[seed],
      hypeCycle: hypeCycleStages[seed],
      forecast: [
        { year: 2024, growth: 10 + seed * 5 },
        { year: 2025, growth: 25 + seed * 8 },
        { year: 2026, growth: 45 + seed * 10 },
        { year: 2027, growth: 70 + seed * 5 },
        { year: 2028, growth: 95 - seed * 2 }
      ],
      insights: [
        `Rapid adoption of ${tech} in enterprise sectors`,
        "Significant venture capital investment in this space",
        "Integration with existing cloud and data infrastructure"
      ],
      risks: [
        `Regulatory uncertainty surrounding ${tech} applications`,
        "High initial implementation and R&D costs",
        "Shortage of specialized talent to drive innovation"
      ],
      opportunities: [
        "Optimization of global supply chain logistics",
        "Enhanced customer experience through advanced personalization",
        "New revenue streams via innovative data monetization"
      ]
    };
  }
}
